// AUTO-GENERATED by scripts/extract_tokens.mjs — do not edit directly
// Source: assets/nwg-tokens.css
// 1 inch = 96 px  |  slide canvas: 1280×720 px = 13.333×7.5 in

export const SLIDE_W = 13.333;
export const SLIDE_H = 7.5;
export const PX_PER_INCH = 96;

export function pxToIn(px) { return px / PX_PER_INCH; }
export function inToPx(inches) { return Math.round(inches * PX_PER_INCH); }

const _base = {
  p900: '2B0A4A', p800: '3D0F66', p700: '4F1783', p600: '5E1B9C', p500: '7B2CBF',
  p400: '9D5BD6', p300: 'BD91E5', p200: 'D9BDF0', p100: 'ECDCF7', p050: 'F7EFFC',
  gold:   'FDAB1F',
  n0:     'FFFFFF', n100: 'F3F3F5', n300: 'D7D7DE', n500: '8C8C97',
  n700:   '4E4E5A', n900: '1F1B2E',
  ok:     '4FA86A', warn: 'F3A73A', danger: 'E43E6E',
  // semantic aliases used by components
  white:  'FFFFFF', ink:   '1F1B2E', muted: '4E4E5A', line:  'D7D7DE',
};

export const palettes = {
  'nwg-purple-default': { ..._base },
  'cool-blue': {
    ..._base,
    p900: '022A40', p800: '065A82', p700: '1C7293', p600: '027D9A', p500: '028090',
    p400: '4AACCD', p300: '87CCDF', p200: 'B8E2EE', p100: 'DDF3F6', p050: 'F0FAFC',
  },
  mono: {
    ..._base,
    p900: '1F1B2E', p800: '2C2C35', p700: '4E4E5A', p600: '6C6C77', p500: '8C8C97',
    p400: 'ABABB4', p300: 'C8C8CF', p200: 'E0E0E5', p100: 'F3F3F5', p050: 'FAFAFA',
  },
};

/** Return the hex token map for a given palette id. Falls back to nwg-purple-default. */
export function getTokens(palette = 'nwg-purple-default') {
  return palettes[palette] || palettes['nwg-purple-default'];
}

/** CSS var(--token) string for use inside HTML component fragments. */
export function cssVar(token) { return `var(--${token})`; }
