#!/usr/bin/env node
/**
 * Parses assets/nwg-tokens.css and regenerates lib/tokens.mjs.
 * Run whenever nwg-tokens.css changes.
 * Usage: node scripts/extract_tokens.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const skillRoot = path.resolve(__dirname, '..');
const cssPath = path.join(skillRoot, 'assets', 'nwg-tokens.css');
const outPath = path.join(skillRoot, 'lib', 'tokens.mjs');

const css = fs.readFileSync(cssPath, 'utf8');
const base = {};

for (const [, name, value] of css.matchAll(/--([a-z0-9-]+)\s*:\s*#([0-9a-fA-F]{3,6})/g)) {
  let hex = value;
  if (hex.length === 3) hex = hex.split('').map(c => c + c).join('');
  base[name.replace(/-([a-z0-9])/g, (_, c) => c)] = hex.toUpperCase();
}

if (!base.n0) base.n0 = 'FFFFFF';
base.white = 'FFFFFF';
base.ink   = base.n900 || '1F1B2E';
base.muted = base.n700 || '4E4E5A';
base.line  = base.n300 || 'D7D7DE';

const lines = Object.entries(base).map(([k, v]) => `  ${k}: '${v}',`).join('\n');

const content = `// AUTO-GENERATED by scripts/extract_tokens.mjs — do not edit directly
// Source: assets/nwg-tokens.css
// 1 inch = 96 px  |  slide canvas: 1280×720 px = 13.333×7.5 in

export const SLIDE_W = 13.333;
export const SLIDE_H = 7.5;
export const PX_PER_INCH = 96;

export function pxToIn(px) { return px / PX_PER_INCH; }
export function inToPx(inches) { return Math.round(inches * PX_PER_INCH); }

const _base = {
${lines}
};

export const palettes = {
  'nwg-purple-default': { ..._base },
  'cool-blue': {
    ..._base,
    p900: '022A40', p800: '065A82', p700: '1C7293', p600: '027D9A', p500: '028090',
    p400: '4AACCD', p300: '87CCDF', p200: 'B8E2EE', p100: 'DDF3F6', p050: 'F0FAFC',
  },
  mono: {
    ..._base,
    p900: '1F1B2E', p800: '2C2C35', p700: '4E4E5A', p600: '6C6C77', p500: '8C8C97',
    p400: 'ABABB4', p300: 'C8C8CF', p200: 'E0E0E5', p100: 'F3F3F5', p050: 'FAFAFA',
  },
};

/** Return the hex token map for a given palette id. Falls back to nwg-purple-default. */
export function getTokens(palette = 'nwg-purple-default') {
  return palettes[palette] || palettes['nwg-purple-default'];
}

/** CSS var(--token) string for use inside HTML component fragments. */
export function cssVar(token) { return \`var(--\${token})\`; }
`;

fs.writeFileSync(outPath, content);
console.log('Wrote', outPath);
